Z01R: Drop system sensor blobs
We don't need to include them and they cause elf check errors anyways

error: vendor/asus/Z01R/Android.bp:7100:1: module "prebuilt_libsns_device_mode_stub" already defined
       vendor/asus/Z01R/Android.bp:95:1 <-- previous definition here
error: vendor/asus/Z01R/Android.bp:7143:1: module "prebuilt_libsns_fastRPC_util" already defined
       vendor/asus/Z01R/Android.bp:137:1 <-- previous definition here
error: vendor/asus/Z01R/Android.bp:7184:1: module "prebuilt_libsns_low_lat_stream_stub" already defined
       vendor/asus/Z01R/Android.bp:175:1 <-- previous definition here
Change-Id: I0cf1283858f29a22e61f2e269de3b16b73f48af4